ipAddress: "10.234.170.128"
server:
  port: 8089
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/es_projects
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    host: ${ipAddress}
    port: 5672
    username: guest
    password: guest
  redis:
    host: ${ipAddress}
    port: 6379
    password: 990416
    database: 0
    timeout: 1800000

logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: cn.itcast.hotel.pojo